// NOT USED YET - GENERATED BY CHAT GPT
import { defineStore } from 'pinia';

import { fetchWrapper } from '@/helpers';

const baseUrl = `${import.meta.env.VITE_API_URL}/api/user`;

export const userStore = defineStore({
    id: 'instruction',
    state: () => ({
        instructions: {},
        instruction: {}
    }),
    actions: {
      async find() {
        //   this.instruction = { loading: true };
          this.instructions = { loading: true };
          fetchWrapper.get(`${baseUrl}`)
              .then(res => this.instructions = res.data)
              .catch(error => this.instructions = { error })
      },
      async findSlug(slug) {
        //   this.instructions = { loading: true };
          this.instruction = { loading: true };
          fetchWrapper.get(`${baseUrl}?filters[slug][$eq]=${slug}`)
              .then(res => this.instruction = res.data[0])
              .catch(error => this.instruction = { error })
      },
      async update(id, data) {
        return fetchWrapper.put(`${baseUrl}/${id}?populate=*`,{data: data})
            .then(res => {
                // v5 returns a flat entry; update it in the list if present.
                const updated = res.data;
                if (Array.isArray(this.instructions)) {
                    const idx = this.instructions.findIndex(v => v.id == updated.id);
                    if (idx !== -1) this.instructions[idx] = updated;
                }
            })
            .catch(this.handleError);
      },
      async register(data) {
        return fetchWrapper.post(`${baseUrl}?populate=*`,{data:data})
            .then(res => {
                this.instructions = res.data;
            })
            .catch(this.handleError);
      },
      async delete(id) {
        return fetchWrapper.delete(`${baseUrl}/${id}`)
            .then(res => {
                console.log("delete: ", res)
            })
            .catch(this.handleError);
      }
    }

});
